/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package votingsystemdb;

/**
 *
 * @author Admin
 */

import java.sql.*;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

public class Vote extends javax.swing.JFrame {

    /**
     * Creates new form Vote
     */
    public Vote() {
        initComponents();
    }
    private int currentVotersID;
    
    public Vote(int votersID) {
    this.currentVotersID = votersID;
    initComponents();
    checkIfAlreadyVoted(); // <-- call this check right after GUI loads
    }
    
    
    private void checkIfAlreadyVoted() {
        try (Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/vms", "root", "")) {
            String sql = "SELECT has_voted FROM voters WHERE votersID = ?";
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setInt(1, currentVotersID);
            ResultSet rs = ps.executeQuery();

            if (rs.next() && rs.getBoolean("has_voted")) {
                JOptionPane.showMessageDialog(this, "You have already voted.");
                submitButton.setEnabled(false);
                disableAllRadioButtons();
            }

            rs.close();
            ps.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error checking vote status: " + e.getMessage());
        }
    }

    private void disableAllRadioButtons() {
        kikoBarzaga.setEnabled(false);
        tarahPacardo.setEnabled(false);
        carlBrynne.setEnabled(false);
        michaelCabs.setEnabled(false);
        zheyAnn.setEnabled(false);
        jRadioButton7.setEnabled(false);
        jRadioButton8.setEnabled(false);
        jRadioButton9.setEnabled(false);
    }
    
    Connection conn;
    Statement stmt;


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        baranggayCaptain = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        kikoBarzaga = new javax.swing.JRadioButton();
        tarahPacardo = new javax.swing.JRadioButton();
        carlBrynne = new javax.swing.JRadioButton();
        michaelCabs = new javax.swing.JRadioButton();
        zheyAnn = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jRadioButton9 = new javax.swing.JRadioButton();
        submitButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 204));

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));

        jLabel2.setFont(new java.awt.Font("Montserrat ExtraBold", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("VOTE");

        baranggayCaptain.add(kikoBarzaga);
        kikoBarzaga.setFont(new java.awt.Font("Montserrat ExtraBold", 1, 36)); // NOI18N
        kikoBarzaga.setForeground(new java.awt.Color(0, 0, 0));
        kikoBarzaga.setText("Kiko Barzaga");
        kikoBarzaga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kikoBarzagaActionPerformed(evt);
            }
        });

        baranggayCaptain.add(tarahPacardo);
        tarahPacardo.setFont(new java.awt.Font("Montserrat ExtraBold", 1, 36)); // NOI18N
        tarahPacardo.setForeground(new java.awt.Color(0, 0, 0));
        tarahPacardo.setText("Tarah Pacardo");
        tarahPacardo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tarahPacardoActionPerformed(evt);
            }
        });

        baranggayCaptain.add(carlBrynne);
        carlBrynne.setFont(new java.awt.Font("Montserrat ExtraBold", 1, 36)); // NOI18N
        carlBrynne.setForeground(new java.awt.Color(0, 0, 0));
        carlBrynne.setText("Carl Brynne");
        carlBrynne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carlBrynneActionPerformed(evt);
            }
        });

        baranggayCaptain.add(michaelCabs);
        michaelCabs.setFont(new java.awt.Font("Montserrat ExtraBold", 1, 36)); // NOI18N
        michaelCabs.setForeground(new java.awt.Color(0, 0, 0));
        michaelCabs.setText("Michael Cabs");
        michaelCabs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                michaelCabsActionPerformed(evt);
            }
        });

        baranggayCaptain.add(zheyAnn);
        zheyAnn.setFont(new java.awt.Font("Montserrat ExtraBold", 1, 36)); // NOI18N
        zheyAnn.setForeground(new java.awt.Color(0, 0, 0));
        zheyAnn.setText("Zhey Ann-chan");
        zheyAnn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zheyAnnActionPerformed(evt);
            }
        });

        baranggayCaptain.add(jRadioButton7);
        jRadioButton7.setFont(new java.awt.Font("Montserrat ExtraBold", 1, 36)); // NOI18N
        jRadioButton7.setForeground(new java.awt.Color(0, 0, 0));
        jRadioButton7.setText("AJ Salcedo");
        jRadioButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton7ActionPerformed(evt);
            }
        });

        baranggayCaptain.add(jRadioButton8);
        jRadioButton8.setFont(new java.awt.Font("Montserrat ExtraBold", 1, 36)); // NOI18N
        jRadioButton8.setForeground(new java.awt.Color(0, 0, 0));
        jRadioButton8.setText("Rameses Moises");
        jRadioButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton8ActionPerformed(evt);
            }
        });

        baranggayCaptain.add(jRadioButton9);
        jRadioButton9.setFont(new java.awt.Font("Montserrat ExtraBold", 1, 36)); // NOI18N
        jRadioButton9.setForeground(new java.awt.Color(0, 0, 0));
        jRadioButton9.setText("Tarah Barzaga");
        jRadioButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton9ActionPerformed(evt);
            }
        });

        submitButton.setBackground(new java.awt.Color(0, 204, 204));
        submitButton.setFont(new java.awt.Font("Lato Black", 1, 24)); // NOI18N
        submitButton.setForeground(new java.awt.Color(204, 255, 255));
        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        cancelButton.setBackground(new java.awt.Color(255, 51, 102));
        cancelButton.setFont(new java.awt.Font("Lato Black", 1, 24)); // NOI18N
        cancelButton.setForeground(new java.awt.Color(204, 255, 255));
        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(michaelCabs, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(carlBrynne, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tarahPacardo, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kikoBarzaga, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jRadioButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(zheyAnn, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22))
                    .addComponent(jRadioButton8, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(37, 37, 37))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(363, 363, 363)
                        .addComponent(jLabel2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(317, 317, 317)
                        .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(submitButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel2)
                .addGap(52, 52, 52)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(zheyAnn, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(kikoBarzaga, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tarahPacardo, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(carlBrynne, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(michaelCabs, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(51, 51, 51)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton)
                    .addComponent(submitButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(64, 64, 64))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kikoBarzagaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kikoBarzagaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kikoBarzagaActionPerformed

    private void tarahPacardoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tarahPacardoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tarahPacardoActionPerformed

    private void carlBrynneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carlBrynneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_carlBrynneActionPerformed

    private void michaelCabsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_michaelCabsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_michaelCabsActionPerformed

    private void zheyAnnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zheyAnnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_zheyAnnActionPerformed

    private void jRadioButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton7ActionPerformed

    private void jRadioButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton8ActionPerformed

    private void jRadioButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton9ActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        // TODO add your handling code here:
       String selectedCandidate = null;

        if (kikoBarzaga.isSelected()) selectedCandidate = "Kiko Barzaga";
        else if (tarahPacardo.isSelected()) selectedCandidate = "Tarah Pacardo";
        else if (carlBrynne.isSelected()) selectedCandidate = "Carl Brynne";
        else if (michaelCabs.isSelected()) selectedCandidate = "Michael Cabs";
        else if (zheyAnn.isSelected()) selectedCandidate = "Zhey Ann-chan";
        else if (jRadioButton7.isSelected()) selectedCandidate = "AJ Salcedo";
        else if (jRadioButton8.isSelected()) selectedCandidate = "Rameses Moises";
        else if (jRadioButton9.isSelected()) selectedCandidate = "Tarah Barzaga";

        if (selectedCandidate == null) {
            JOptionPane.showMessageDialog(this, "Please select a candidate before submitting your vote.");
            return;
        }

        try {
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/vms", "root", "");

            // Update candidate vote count
            String updateVoteSQL = "UPDATE candidate SET votes = votes + 1 WHERE name = ?";
            PreparedStatement voteStmt = conn.prepareStatement(updateVoteSQL);
            voteStmt.setString(1, selectedCandidate);
            int voteUpdated = voteStmt.executeUpdate();

            if (voteUpdated > 0) {
                // Get candidate ID from selected name
                String getCandidateIDQuery = "SELECT candidateID FROM candidate WHERE name = ?";
                PreparedStatement getIDStmt = conn.prepareStatement(getCandidateIDQuery);
                getIDStmt.setString(1, selectedCandidate);
                ResultSet idResult = getIDStmt.executeQuery();

                int candidateID = -1;
                if (idResult.next()) {
                    candidateID = idResult.getInt("candidateID");
                }
                idResult.close();
                getIDStmt.close();

                if (candidateID != -1) {
                    // Insert into ballot table
                    String insertBallotSQL = "INSERT INTO ballot (votersID, candidateID) VALUES (?, ?)";
                    PreparedStatement ballotStmt = conn.prepareStatement(insertBallotSQL);
                    ballotStmt.setInt(1, currentVotersID);
                    ballotStmt.setInt(2, candidateID);
                    ballotStmt.executeUpdate();
                    ballotStmt.close();
                }

                // Update voter as has_voted
                String updateVoterSQL = "UPDATE voters SET has_voted = TRUE WHERE votersID = ?";
                PreparedStatement voterStmt = conn.prepareStatement(updateVoterSQL);
                voterStmt.setInt(1, currentVotersID);
                voterStmt.executeUpdate();
                voterStmt.close();

                // Show receipt
                LocalDateTime now = LocalDateTime.now();
                DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");

                String receipt = "\uD83D\uDDF3 Vote Receipt\n\n" +
                    "Voter ID: " + currentVotersID + "\n" +
                    "Candidate: " + selectedCandidate + "\n" +
                    "Time: " + now.format(formatter) + "\n\n" +
                    "Thank you for voting!";

                JOptionPane.showMessageDialog(this, receipt, "Vote Submitted", JOptionPane.INFORMATION_MESSAGE);
                disableAllRadioButtons();
                submitButton.setEnabled(false);
            } else {
                JOptionPane.showMessageDialog(this, "Failed to record vote. Candidate not found.");
            }

            voteStmt.close();
            conn.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error submitting vote: " + e.getMessage());
        }
    }//GEN-LAST:event_submitButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        this.dispose(); // closes the current form
        
        newlogin login = new newlogin();
        login.setVisible(true);
    }//GEN-LAST:event_cancelButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vote().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup baranggayCaptain;
    private javax.swing.JButton cancelButton;
    private javax.swing.JRadioButton carlBrynne;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRadioButton9;
    private javax.swing.JRadioButton kikoBarzaga;
    private javax.swing.JRadioButton michaelCabs;
    private javax.swing.JButton submitButton;
    private javax.swing.JRadioButton tarahPacardo;
    private javax.swing.JRadioButton zheyAnn;
    // End of variables declaration//GEN-END:variables
}
